### ISSUE TITLE
Opening post gives 404

### ISSUE THREAD

**Issue by alexsaaf** [dldx/hpstr-hugo-theme#6]
I am using the example site provided with the theme, but when I click the title of a post I get 404. The url is for example: http://localhost:1313/posts/background-image/. I generated the page and within posts, there are no html files for the individual posts. 

Does the theme not have a way to show a single post (Similarly to how it can display the About page) ? I might just be doing something dumb, but I can't figure it out.

**Comment by dldx** [comment]
Hi Alex, I'm not sure what you mean exactly. It does indeed show a single page for a post, like here: https://dldx.github.io/hpstr-hugo-theme/posts/background-image.

Is that not what you wanted? Check that you have the right files in your content folder. You can just copy and paste all the files from the [exampleSite folder](https://github.com/dldx/hpstr-hugo-theme/tree/master/exampleSite) into your main hugo folder, which should create everything you need to get started.

**Comment by alexsaaf** [comment]
That is exactly the behavior I wanted yes, but when I copy the example site I get 404 not found when trying to get the same result. Everything else seems to work. I tried adding a new post (hugo new posts/test.md) and it worked. I noticed a bit of a difference in the files. The meta data of the new past looks like: 

```
+++
Categories = ["Development","GoLang"]
Description = ""
Tags = ["Development","golang"]
date = "2017-04-26T07:17:09+02:00"
menu = "main"
title = "test"
+++
```
and the meta data in the files from the theme:

```
---
layout: post
title: Syntax Highlighting Post
description: "Demo post displaying the various ways of highlighting code in Markdown."
date: 2013-08-16
lastmod: 2016-09-05
tags: [sample post, code, highlighting]
image:
  feature: /images/abstract-10.jpg
  credit: dargadgetz
  creditlink: http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/
---
```

Not sure if the small differences matter (Very new to HUGO), but I got my page working now at least.
